# Generated by Django 2.1.5 on 2020-11-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
